# Generated by Django 4.2.1 on 2023-06-08 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='posts_set', to='post.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
