# Generated by Django 4.2.1 on 2023-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
