# Generated by Django 4.2.1 on 2023-06-14 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blocked_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_accounts_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='links',
            field=models.TextField(blank=True, null=True, verbose_name='🏙 Social links'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='Is verified account ☑️'),
        ),
    ]
