# Generated by Django 4.2.1 on 2023-06-15 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_photos'),
        ('account', '0004_account_blocked_accounts_account_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(verbose_name='🥳 Birth date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_accounts_set', to=settings.AUTH_USER_MODEL, verbose_name='Blocked accounts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='💠 Is admin'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='⛔️ Is account blocked'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='🛠 Is moderator'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='Is verified account 💼'),
        ),
        migrations.AlterField(
            model_name='account',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='posts_set', to='post.post', verbose_name='Published posts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers_set', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
    ]
