# Generated by Django 4.2.1 on 2023-06-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='🥳 Birth date'),
        ),
    ]
