# Generated by Django 4.2.1 on 2023-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='its_reply',
            new_name='is_reply',
        ),
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Пост було редаговано'),
        ),
    ]
