# Generated by Django 4.2.1 on 2023-06-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('post', '0003_rename_its_reply_post_is_reply_post_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photo.photo', verbose_name='Фотографії'),
        ),
    ]
